version: '3'
services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=planet4.dev --docker.watch
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${APP_HOSTNAME:-test.planet4.dev}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  redis:
    image: redis:4-alpine
    networks:
      - local
    # volumes:
    #   - ./persistence/redis:/data
    labels:
      traefik.enable: "false"

  db:
    image: mysql:5.7
    env_file:
      - ./db.env
    volumes:
      - ./persistence/mysql:/var/lib/mysql:cached
    networks:
      - db
    labels:
      traefik.enable: "false"

  php-fpm:
    image: gcr.io/planet-4-151612/wordpress:${APP_BUILD_TAG:-develop}
    depends_on:
      - db
      - redis
    networks:
      - local
      - db
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    volumes:
      - ./persistence/app:/app/source:cached
      - ./secrets/wp-stateless-media-key.json:/app/secrets/wp-stateless-media-key.json:ro
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - APP_HOSTNAME=${APP_HOSTNAME:-test.planet4.dev}
      - GIT_REF=develop
      - GIT_SOURCE=https://github.com/greenpeace/planet4-base
      - NEWRELIC_LICENSE=${NEWRELIC_LICENSE:-false}
      - WP_DEFAULT_CONTENT=${WP_DEFAULT_CONTENT:-false}
      - WP_REDIS_ENABLED=${WP_REDIS_ENABLED:-true}
      - WP_SITE_HOME=${APP_HOSTNAME:-test.planet4.dev}
      - WP_SITE_URL=${APP_HOSTNAME:-test.planet4.dev}
      - WP_STATELESS_MEDIA_BUCKET=${APP_HOSTNAME:-test-planet4-dev}
      - WP_STATELESS_MEDIA_ENABLED=${WP_STATELESS_MEDIA_ENABLED:-true}
    env_file:
      - ./app.env
      - ./db.env
    labels:
      traefik.enable: "false"

  openresty:
    image: gcr.io/planet-4-151612/openresty:${OPENRESTY_BUILD_TAG:-develop}
    depends_on:
      - php-fpm
      - traefik
      - redis
    networks:
      - local
      - proxy
    volumes:
      - ./persistence/app:/app/source:cached
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - PAGESPEED_ENABLED=${PAGESPEED_ENABLED:-false}
      - APP_HOSTNAME=${APP_HOSTNAME:-test.planet4.dev}
      - PHP_ENABLED=true
    labels:
      traefik.backend: "openresty"
      traefik.frontend.rule: "Host:${APP_HOSTNAME:-test.planet4.dev}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
      - traefik
    env_file:
      - ./db.env
    volumes:
      - ./persistence/pma:/sessions
    networks:
      - db
      - proxy
    labels:
      traefik.backend: "pma"
      traefik.frontend.rule: "Host:pma.${APP_HOSTNAME:-test.planet4.dev}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  elasticsearch:
    image: es:6.1
    networks:
      - local
    labels:
      traefik.enable: "false"

  smtp:
    image: gcr.io/planet-4-151612/exim:${SMTP_BUILD_TAG:-develop}
    networks:
      - local
    labels:
      traefik.enable: "false"


networks:
  local:
  db:
  proxy:
    driver: bridge
