version: '3'
services:
  app:
    image: gcr.io/planet-4-151612/p4-app-gpi:develop
    # Modify container DNS if behind a corporate firewall which restricts dns
    # Resolves timeouts accessing remote API
    # dns:
    #   - 192.168.2.1
    #   - 8.8.8.8
    #   - 8.8.4.4
    ports:
      - "80:80"
    volumes:
      - ./persistence/app:/app/source/public:cached
    env_file:
      - ./app.env
      - ./db.env
    depends_on:
      - mysql
  mysql:
    image: mysql
    env_file:
      - ./db.env
    volumes:
      - ./persistence/mysql:/var/lib/mysql:cached
