version: '3'
services:
  traefik:
    image: traefik:latest
    command: --web --docker --docker.domain=planet4.dev --docker.watch --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  db:
    image: mysql:5.6
    env_file:
      - ./db.env
    volumes:
      - ./persistence/mysql:/var/lib/mysql:cached
    networks:
      - db

  app:
    image: gcr.io/planet-4-151612/p4-gpi-app-dev:${APP_BUILD_TAG:-develop}
    networks:
      - local
      - db
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    volumes:
      - ./persistence/app:/app/source/public:cached
    env_file:
      - ./app.env
      - ./db.env
    depends_on:
      - db
    # To force reinstalling Wordpress from composer on container start
    # environment:
    #   - OVERWRITE_FILES=true

  nginx:
    image: gcr.io/planet-4-151612/nginx-pagespeed:${NGINX_BUILD_TAG:-develop}
    networks:
      - local
      - proxy
    volumes:
      - ./persistence/app:/app/www:cached
    env_file:
      - ./app.env
    environment:
      - NGINX_FASTCGI_BACKEND=${NGINX_FASTCGI_BACKEND:-app:9000}
      - PHP_ENABLED=true
      - SSL_ENABLED=false
    labels:
      traefik.backend: "test"
      traefik.frontend.rule: "Host:test.planet4.dev"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"
    depends_on:
      - app
      - traefik

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
      - traefik
    env_file:
      - ./db.env
    volumes:
      - ./persistence/pma:/sessions
    networks:
      - db
      - proxy
    labels:
      traefik.backend: "pma"
      traefik.frontend.rule: "Host:pma.planet4.dev"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"


networks:
  local:
  db:
  proxy:
    driver: bridge
