version: '3'
services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=planet4.dev --docker.watch
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.planet4.dev"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  redis:
    image: redis:4-alpine
    networks:
      - local
    volumes:
      - ./persistence/redis:/data

  db:
    image: mysql:5.7
    env_file:
      - ./db.env
    volumes:
      - ./persistence/mysql:/var/lib/mysql:cached
    networks:
      - db

  app:
    image: gcr.io/planet-4-151612/p4-gpi-app-dev:${APP_BUILD_TAG:-dev-feature-gitrepositories}
    networks:
      - local
      - db
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    volumes:
      - ./persistence/app:/app/source/public:cached
      - ./secrets/wp-stateless-media-key.json:/app/secrets/wp-stateless-media-key.json:ro
    environment:
      - OVERWRITE_FILES=${OVERWRITE_FILES:-false}
    env_file:
      - ./app.env
      - ./db.env
    depends_on:
      - db
      - redis
    # To force reinstalling Wordpress from composer on container start
    # environment:
    #   - OVERWRITE_FILES=true

  redis:
    image: redis:4-alpine
    networks:
      - local
    volumes:
      - ./persistence/redis:/data

  openresty:
    image: gcr.io/planet-4-151612/openresty:${OPENRESTY_BUILD_TAG:-develop}
    networks:
      - local
      - proxy
    volumes:
      - ./persistence/app:/app/www:cached
    env_file:
      - ./app.env
    environment:
      - OPENRESTY_FASTCGI_BACKEND=${OPENRESTY_FASTCGI_BACKEND:-app:9000}
      - PHP_ENABLED=true
      - SSL_ENABLED=false
    labels:
      traefik.backend: "test"
      traefik.frontend.rule: "Host:test.planet4.dev"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"
    depends_on:
      - app
      - traefik
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
      - traefik
    env_file:
      - ./db.env
    volumes:
      - ./persistence/pma:/sessions
    networks:
      - db
      - proxy
    labels:
      traefik.backend: "pma"
      traefik.frontend.rule: "Host:pma.planet4.dev"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  smtp:
    image: gcr.io/planet-4-151612/exim:${SMTP_BUILD_TAG:-develop}
    networks:
      - local
    environment:
      - APP_ENV=develop
    labels:
      traefik.enable: "false"


networks:
  local:
  db:
  proxy:
    driver: bridge
