version: '3'
services:
  traefik:
    image: traefik:1.4
    command: --web --docker --docker.domain=p4.greenpeace.org --docker.watch
    restart: always
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${APP_HOSTNAME:-docker.p4.greenpeace.org}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  redis:
    image: redis:4-alpine
    restart: always
    networks:
      - local
    volumes:
      - ./persistence/redis:/data
    labels:
      traefik.enable: "false"

  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    #command: /cloud_sql_proxy -instances=planet-4-151612:europe-west1:p4-docker-cloudsql-1=tcp:0.0.0.0:3306 -credential_file=/config
    command: /cloud_sql_proxy -instances=planet-4-151612:europe-west1:p4-develop=tcp:0.0.0.0:3306 -credential_file=/config
    restart: always
    volumes:
      - ./secrets/cloudsql/p4-docker-cloudsql-service-account.json:/config
    networks:
      - db
    labels:
      traefik.enable: "false"

  php-fpm:
    image: gcr.io/planet-4-151612/p4-gpi-app-dev:${APP_BUILD_TAG:-develop}
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - local
      - db
    dns:
      - ${DNS_RESOLVER:-8.8.8.8}
    volumes:
      - ./persistence/app:/app/source/public:cached
      - ./secrets/wp-stateless/wp-stateless-media-key.json:/app/secrets/wp-stateless-media-key.json:ro
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - APP_HOSTNAME=${APP_HOSTNAME:-docker.p4.greenpeace.org}
      - NEWRELIC_LICENSE=${NEWRELIC_LICENSE:-false}
      - WP_REDIS_ENABLED=${WP_REDIS_ENABLED:-true}
      - WP_STATELESS_MEDIA_ENABLED=${WP_STATELESS_MEDIA_ENABLED:-true}
      - WP_SITE_HOME=${APP_HOSTNAME:-docker.p4.greenpeace.org}/international
      - WP_SITE_URL=${APP_HOSTNAME:-docker.p4.greenpeace.org}/international
    env_file:
      - ./app.env
      - ./db.env
    labels:
      traefik.enable: "false"

  openresty:
    image: gcr.io/planet-4-151612/p4-gpi-openresty-dev:${OPENRESTY_BUILD_TAG:-develop}
    restart: always
    depends_on:
      - php-fpm
      - traefik
      - redis
    networks:
      - local
      - proxy
    volumes:
      - ./persistence/app:/app/www:cached
      - ./pagespeed.conf.tmpl:/app/templates/etc/nginx/server.d/10_pagespeed.conf.tmpl
    environment:
      - APP_ENV=${APP_ENV:-develop}
      - PAGESPEED_ENABLED=${PAGESPEED_ENABLED:-true}
      - REDIS_FASTCGI_CACHE_ENABLED=false
      - APP_HOSTNAME=${APP_HOSTNAME:-docker.p4.greenpeace.org}
    labels:
      traefik.backend: "openresty"
      traefik.frontend.rule: "Host:${APP_HOSTNAME:-docker.p4.greenpeace.org}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    depends_on:
      - db
      - traefik
    env_file:
      - ./db.env
    volumes:
      - ./persistence/pma:/sessions
    networks:
      - db
      - proxy
    labels:
      traefik.backend: "pma"
      traefik.frontend.rule: "Host:pma.${APP_HOSTNAME:-docker.p4.greenpeace.org}"
      traefik.docker.network: "planet4dockercompose_proxy"
      traefik.enable: "true"

  smtp:
    image: gcr.io/planet-4-151612/exim:${SMTP_BUILD_TAG:-develop}
    restart: always
    networks:
      - local
    environment:
      - EXIM_SMARTHOST=smtp-relay.gmail.com::587
    labels:
      traefik.enable: "false"
networks:
  local:
  db:
  proxy:
    driver: bridge
