---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  codeception:
    <<: *defaults
    environment:
      APP_IMAGE: gcr.io/planet-4-151612/planet4-base-app:develop
      OPENRESTY_IMAGE: gcr.io/planet-4-151612/planet4-base-openresty:develop
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
            - composer-v1-{{ .Branch }}-{{ .Revision }}
            - composer-v1-{{ .Branch }}
            - composer-v1
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make ci
      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
          paths:
            - defaultcontent
      - run: make test
      - run: make ci-extract-artifacts
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Codeception" notify-job-failure.sh

workflows:
  version: 2
  test:
    jobs:
      - codeception
