---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint

workflows:
  version: 2
  test:
    jobs:
      - lint
