---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make lint
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Lint" notify-job-failure.sh
  codeception:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
            - composer-v1-{{ .Branch }}-{{ .Revision }}
            - composer-v1-{{ .Branch }}
            - composer-v1
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make ci test ci-extract-artifacts
      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ .Revision }}-{{ .BuildNum }}
          paths:
            - defaultcontent
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var
      - store_test_results:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: TYPE="Codeception" notify-job-failure.sh

workflows:
  version: 2
  test:
    jobs:
      - lint
      - codeception
